// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: store_file/v1/file_stored.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Extension     string                 `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStored) Reset() {
	*x = FileStored{}
	mi := &file_store_file_v1_file_stored_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStored) ProtoMessage() {}

func (x *FileStored) ProtoReflect() protoreflect.Message {
	mi := &file_store_file_v1_file_stored_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStored.ProtoReflect.Descriptor instead.
func (*FileStored) Descriptor() ([]byte, []int) {
	return file_store_file_v1_file_stored_proto_rawDescGZIP(), []int{0}
}

func (x *FileStored) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileStored) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileStored) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStored) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *FileStored) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

var File_store_file_v1_file_stored_proto protoreflect.FileDescriptor

const file_store_file_v1_file_stored_proto_rawDesc = "" +
	"\n" +
	"\x1fstore_file/v1/file_stored.proto\x12\rstore_file.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\n" +
	"FileStored\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x1c\n" +
	"\textension\x18\x05 \x01(\tR\textensionBEZCgithub.com/kinneko-de/poc-mongodb-changestream/golang/store_file/v1b\x06proto3"

var (
	file_store_file_v1_file_stored_proto_rawDescOnce sync.Once
	file_store_file_v1_file_stored_proto_rawDescData []byte
)

func file_store_file_v1_file_stored_proto_rawDescGZIP() []byte {
	file_store_file_v1_file_stored_proto_rawDescOnce.Do(func() {
		file_store_file_v1_file_stored_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_file_v1_file_stored_proto_rawDesc), len(file_store_file_v1_file_stored_proto_rawDesc)))
	})
	return file_store_file_v1_file_stored_proto_rawDescData
}

var file_store_file_v1_file_stored_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_file_v1_file_stored_proto_goTypes = []any{
	(*FileStored)(nil),            // 0: store_file.v1.FileStored
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_store_file_v1_file_stored_proto_depIdxs = []int32{
	1, // 0: store_file.v1.FileStored.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_store_file_v1_file_stored_proto_init() }
func file_store_file_v1_file_stored_proto_init() {
	if File_store_file_v1_file_stored_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_file_v1_file_stored_proto_rawDesc), len(file_store_file_v1_file_stored_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_file_v1_file_stored_proto_goTypes,
		DependencyIndexes: file_store_file_v1_file_stored_proto_depIdxs,
		MessageInfos:      file_store_file_v1_file_stored_proto_msgTypes,
	}.Build()
	File_store_file_v1_file_stored_proto = out.File
	file_store_file_v1_file_stored_proto_goTypes = nil
	file_store_file_v1_file_stored_proto_depIdxs = nil
}
